import psycopg2 as ps

conn = ps.connect(database = 'hackncdb', host = 'localhost', user = 'postgres', password = '1234', port = '1234')
cursor = conn.cursor()

cursor.execute('''CREATE TABLE stores(
     id int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name varchar(255) NOT NULL,
     chain varchar(255) NOT NULL,
     address varchar(255) NOT NULL)
     ''')
cursor.execute('''CREATE TABLE items(
    id int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    value DECIMAL(12,2),
    image varchar(511),
    url varchar(511) NOT NULL,
    sid int NOT NULL REFERENCES stores(id)    
)''')
cursor.execute('''CREATE TABLE users(
    id int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    username varchar(255) NOT NULL,
    address varchar(255) NOT NULL)'''
)
 
cursor.execute('''CREATE TABLE list(
    uid int NOT NULL REFERENCES users(id),
    pid int NOT NULL REFERENCES items(id),
    quantity int NOT NULL
)''')

conn.commit()